library(dplyr)
tabela <- read.csv('household_power_consumption.txt', sep=';', na.strings='?')
tabela$DateTime <- paste(tabela$Date, tabela$Time)
tabela$DateTime <- as.Date(tabela$DateTime, format = "%d/%m/%Y %H:%M:%S")
subsetted <- filter(tabela, DateTime >= as.Date("2007-02-01 00:00:00"), DateTime < as.Date("2007-02-03 00:00:00"))
png(file="plot2.png",width=480,height=480)
subsetted$newdate = strptime(paste(subsetted$Date, subsetted$Time, sep = " "),"%d/%m/%Y %H:%M:%S")
with (subsetted, {plot(newdate, Global_active_power, type='l', ylab="Global Active Power (kilowatts)", xlab="")})
dev.off()